### ISSUE TITLE
Turn center fuel pumps on

### ISSUE THREAD

**Issue by daniol** [daniol/xsaitekpanels-zibo#1]
If we detect that the center tanks have more than 726 kg of fuel, the "fuel pumps ON" switch should turn also the center pumps on.

**Comment by CyberGuerro** [comment]
If I remember correctly, by default if you open center fuel pumps and there's no sufficient fuel, the system switch off pumps, like while you fly and central tanks become empty.
In conclusion I think that we can switch on/off all pumps, then the system make the rest :-)

**Comment by daniol** [comment]
Yes, however the weight check it's only to add more realism and avoid wrong configurations automatically. According to some video of Mentour (that I cannot find anymore), you should never run the center pumps if the warning light is illuminated, as it could bring you to a motor failure. In Zibo, if you let them open, the center tank will drop until 0 kg.

Some references I found quickly:

https://ibb.co/KFSDfWv  (some airlines allow a lower limit)

https://image.slidesharecdn.com/fuel-130506062542-phpapp02/95/b737-ng-fuel-system-15-638.jpg?cb=1443782803 ("_Intentional running of a centre tank fuel pump (lowpressure light illuminated) is prohibited_")

**Comment by CyberGuerro** [comment]
OK, as you want,  more realism is better  :-)
But before create v1.13, it's better wait for 1 week meanwhile could arrive other changes/enhancement :-)
What do you think about it?

**Comment by CyberGuerro** [comment]
@daniol, if you want to relesase 1.13 with this feature I think that 24 days was past and it's time to close this issue.
About fuel condition, I read in checklist that limit is 453Kg, so I think you could change initial limit of  **726 kg** in **453 kg**.

This is the checklist
[clist.txt](https://github.com/daniol/xsaitekpanels-zibo/files/4911203/clist.txt)

**Comment by daniol** [comment]
Ok, I will implement this on weekend.

**Comment by daniol** [comment]
Hello @CyberGuerro . I created a merge request with the suggested changes.
I did some tests and it's working here. Can you please test it in X-Plane?
The branch is named "1_fuel"; you can download from here: https://github.com/daniol/xsaitekpanels-zibo/tree/1_fuel
If everything works fine, you can merge it ("pull request 2") and I will create a new "release".
Thanks.
