### ISSUE TITLE
Set also isolation valve with cowl switch

### ISSUE THREAD

**Issue by daniol** [daniol/xsaitekpanels-zibo#4]
Currently the cowl switch is assigned to the left and right packs. It would be helpful to assign also the isolation valve to this switch, as this steps are done together in the checklists.

**Cowl (open)**:
L pack OFF (0)
R pack OFF (0)
Isolation valve OPEN (2)

**Close**:
L pack AUTO (1)
R pack AUTO (1)
Isolation valve AUTO (1)

Datarefs:
```
LEFT PACK          0-off, 1-auto, 2-high          laminar/B738/air/l_pack_pos
RIGHT PACK         0-off, 1-auto, 2-high          laminar/B738/air/r_pack_pos
ISOLATION VALVE    0-close, 1-auto, 2-open        laminar/B738/air/isolation_valve_pos
```
Commands:
```
laminar/B738/toggle_switch/l_pack_up		L PACK up
laminar/B738/toggle_switch/l_pack_dn		L PACK down
laminar/B738/toggle_switch/r_pack_up		R PACK up
laminar/B738/toggle_switch/r_pack_dn		R PACK down
laminar/B738/toggle_switch/iso_valve_up		ISOLATION VALVE up
laminar/B738/toggle_switch/iso_valve_dn		ISOLATION VALVE down
```

**Comment by CyberGuerro** [comment]
@daniol, are you sure about procedure with isolation valve? I seem to remember that in start engine, only packs are switched off and isolation valve is auto. Could you verify in clist.txt (xcheklist) deployed with zibo?. I’m not sure, so if you are right, do it.

**Comment by daniol** [comment]
You are right. I've found the following references on the Zibo Checklist (Clist.txt):

* Preflight preparation (6/7): 
  * LEFT & RIGHT AIR CONDITIONING PACK: AUTO
  * ISOLATION VALVE: OPEN

* Engine start procedure 
  * LEFT & RIGHT AIR CONDITIONING PACKS: OFF

* Before taxi (just after motor start): 
  * LEFT & RIGHT AIR CONDITIONING PACK: AUTO
  * ISOLATION VALVE: AUTO

* Transit shutdown procedure (2/3)
  * ISOLATION VALVE: OPEN

* Complete shutdown procedure (1/2)
  * LEFT & RIGHT AIR CONDITIONING PACKS: OFF

I was using the short checklist from Fly.aero virtual, which only contains the basics and isn't such detailed: https://flyuk.aero/assets/downloads/resources/checklists/UKV-PRD-B737-CHECKLIST-V2.pdf

The position of the isolation valve does not have any effect on X-Plane, however I will revert my changes, to prevent confusion and add more realism.
