### ISSUE TITLE
Documentation for switches

### ISSUE THREAD

**Issue by daniol** [daniol/xsaitekpanels-zibo#6]
With the last improvements is necessary to describe all the buttons and switches of the multipanel and autopilot, the actions that are linked to and the conditions, furthermore because some of them are not obvious and were changed to simplify checklist tasks or add more realism.

Example:

Switch  | OFF action(s) | ON action(s)  | Remarks
--- | --- | --- | ---
... | ... | ... | ...

We can put this information directly on the README.md or in a separate .md file and include a link on the README.md.

@CyberGuerro: can you assume this work? 😃

**Comment by CyberGuerro** [comment]
@daniol, I think that who make changes, should update documentation.
Unfortunelly I’m far from home and I’m writing you by my iPhone and it’s little difficoult write document with it.. 😓😓😓😓

**Comment by daniol** [comment]
It has low priority, no need to do now :)

**Comment by CyberGuerro** [comment]
Did it. 
Created Configuration.md linked to Readmi.md
