### ISSUE TITLE
there are still some problems

### ISSUE THREAD

**Issue by angleofatack** [daniol/xsaitekpanels-zibo#7]
Firstly the lights and other buttons do not work on the switch panel. Only the landing lights button works but now seems to be working.

But now, The acexsp_Zibo738X_multipanel lua file is quarantined. Active / standby does not change on the radio panel. In multipanel "course CRS" does not change.  Also auto brake locks and cannot be changed. How can I solve these problems? Any tips?

The same problems persist in the zibo 3.43 release and the new version 3.44

**Comment by CyberGuerro** [comment]
Did you verify you have the **LAST & COMPLETE** version of [FlyWithLua](https://forums.x-plane.org/index.php?/files/file/38445-flywithlua-ng-next-generation-edition-for-x-plane-11-win-lin-mac/) and [XSaitekPanels](https://forums.x-plane.org/index.php?/files/file/14646-xsaitekpanels-linwinmac3264/) installed correctly??

**Comment by angleofatack** [comment]
yes I have installed the latest version flywithlua and xsaitek panels.  But still, you can tell how to set it up correctly, maybe there is a mistake.

**Comment by CyberGuerro** [comment]
By what you write, the issue depends by quarantine's script.
Attach flywithlua log and Log.txt please.

**Comment by angleofatack** [comment]
[Log.txt](https://github.com/daniol/xsaitekpanels-zibo/files/5445487/Log.txt)

**Comment by angleofatack** [comment]
[initial_assignments.txt](https://github.com/daniol/xsaitekpanels-zibo/files/5445497/initial_assignments.txt)

**Comment by angleofatack** [comment]
what should I do

**Comment by CyberGuerro** [comment]
These probaly generate erros:
`FlyWithLua Info: The DataRef "bgood/xsaitekpanels/sharedata/integer1" is already handled in variable "Integer1", you want to use it with "XSP_Integer1".
FlyWithLua Info: As long as only one variable wants writable access to the DataRef, it is okay (but you loose performance).
FlyWithLua Error: The variable "XSP_Integer1" wants to write a DataRef, that is already handled by another variable.
FlyWithLua Info: The DataRef "bgood/xsaitekpanels/sharedata/integer2" is already handled in variable "Integer2", you want to use it with "XSP_Integer2".
FlyWithLua Info: As long as only one variable wants writable access to the DataRef, it is okay (but you loose performance).
FlyWithLua Error: The variable "XSP_Integer2" wants to write a DataRef, that is already handled by another variable.
FlyWithLua Info: The DataRef "bgood/xsaitekpanels/sharedata/integer3" is already handled in variable "Integer3", you want to use it with "XSP_Integer3".
FlyWithLua Info: As long as only one variable wants writable access to the DataRef, it is okay (but you loose performance).
FlyWithLua Error: The variable "XSP_Integer3" wants to write a DataRef, that is already handled by another variable.
FlyWithLua Info: The DataRef "bgood/xsaitekpanels/sharedata/integer4" is already handled in variable "Integer4", you want to use it with "XSP_Integer4".
FlyWithLua Info: As long as only one variable wants writable access to the DataRef, it is okay (but you loose performance).
FlyWithLua Error: The variable "XSP_Integer4" wants to write a DataRef, that is already handled by another variable.
FlyWithLua Info: The DataRef "bgood/xsaitekpanels/sharedata/integer5" is already handled in variable "Integer5", you want to use it with "XSP_Integer5".
FlyWithLua Info: As long as only one variable wants writable access to the DataRef, it is okay (but you loose performance).
FlyWithLua Error: The variable "XSP_Integer5" wants to write a DataRef, that is already handled by another variable.
FlyWithLua Info: The DataRef "bgood/xsaitekpanels/sharedata/integer6" is already handled in variable "Integer6", you want to use it with "XSP_Integer6".
FlyWithLua Info: As long as only one variable wants writable access to the DataRef, it is okay (but you loose performance).
FlyWithLua Error: The variable "XSP_Integer6" wants to write a DataRef, that is already handled by another variable.
FlyWithLua Info: The DataRef "bgood/xsaitekpanels/sharedata/integer7" is already handled in variable "Integer7", you want to use it with "XSP_Integer7".
FlyWithLua Info: As long as only one variable wants writable access to the DataRef, it is okay (but you loose performance).
FlyWithLua Error: The variable "XSP_Integer7" wants to write a DataRef, that is already handled by another variable.
FlyWithLua Info: The DataRef "bgood/xsaitekpanels/sharedata/integer8" is already handled in variable "Integer8", you want to use it with "XSP_Integer8".
FlyWithLua Info: As long as only one variable wants writable access to the DataRef, it is okay (but you loose performance).
FlyWithLua Error: The variable "XSP_Integer8" wants to write a DataRef, that is already handled by another variable.
AceXSP: ** Starting AceXSP_Zibo738X MULTIPANEL version 1.13 **
FlyWithLua Info: Finished loading script file C:\Program Files (x86)/Steam/steamapps/common/X-Plane 11/Resources/plugins/FlyWithLua/Scripts/acexsp_Zibo738X_multipanel.lua
FlyWithLua Error: The error seems to be inside of script file C:\Program Files (x86)/Steam/steamapps/common/X-Plane 11/Resources/plugins/FlyWithLua/Scripts/acexsp_Zibo738X_multipanel.lua
FlyWithLua Info: 2nd Moved Bad Script to C:\Program Files (x86)/Steam/steamapps/common/X-Plane 11/Resources/plugins/FlyWithLua/Scripts (Quarantine)/acexsp_Zibo738X_multipanel.lua`

It seems that you have a script that use same dataref: 
`FlyWithLua Info: The DataRef "**bgood/xsaitekpanels/sharedata/integer1**" is already handled in variable "Integer1", you want to use it with "XSP_Integer1".`

I suggest you to remove ALL unnecessary scripts and search which remaining script use those datarefs and disable it.

**Comment by angleofatack** [comment]
So what are the files and scripts I need to remove?

**Comment by angleofatack** [comment]
![Ekran Görüntüsü (269)](https://user-images.githubusercontent.com/73531738/97308845-5ec15900-1872-11eb-82d3-5df5b0ba0dd6.png)

These are the lua files I use

**Comment by CyberGuerro** [comment]
I suggest you to REMOVE ALL as first step, then install xSaitekPanels then this package, then all others one by one.

**Comment by angleofatack** [comment]
hi again, I did as you said ''The acexsp_Zibo738X_multipanel lua file'' is no longer quarantined but still In multipanel "course CRS" does not change and the button on the switch panel do not work, only the landing lights. 

[Log.txt](https://github.com/daniol/xsaitekpanels-zibo/files/5445752/Log.txt)

**Comment by angleofatack** [comment]
only the landing lights and beacon light works in switch  panel

**Comment by angleofatack** [comment]
and Auto brake not working

**Comment by CyberGuerro** [comment]
Have you verified whit zibo 3.43.18 (I've not verified with 3.44.1 yet)?
With 3.43.18 all works like a charm (I flyed more times with that version). If you have problem against with that version, I think you have something else wrong (but I can't know what), the only one solution is to reinstall FLYWITHLUA, XSAITEKPANELS and this package following the istructions.
I'm sorry I can't help you more than this.

**Comment by angleofatack** [comment]
Can you explain all the steps you have done one by one?

**Comment by angleofatack** [comment]
There must be mistakes somewhere. So what could be the reason for the auto brake not working?

**Comment by CyberGuerro** [comment]
Reinstall FLYWITHLUA, XSAITEKPANELS and this package **_following the istructions._**
I'm sorry I can't help you more than this.

**Comment by angleofatack** [comment]
''following the istructions '' Like I told you istructions don't work. It would be nice if you can explain how you did it.

**Comment by angleofatack** [comment]
step by step

**Comment by CyberGuerro** [comment]
I followed instructions nothing else. I have no time to replicate what are written in "install instructions"
Are you sure to have followed all instructions of all plugins/packages and that all your wired connection of your devices a correct & work?

**Comment by angleofatack** [comment]
is there anyone to help? where are these developers?

**Comment by CyberGuerro** [comment]
I'm one of the developers and here IT WORKS PERFECTLY (just tested with Zibo 3.44.1).
Issue is not of this package but most probably it depends by your X-Plane 11 installation (FlyWithLua, XSaitekPanels and saitek drivers included).
I'm very sorry for you. I hope you will solve your problem soon, unfortunelly not here.

**Comment by CyberGuerro** [comment]
Not depending from this project.
